/*
 * This source file was generated by the Gradle 'init' task
 */
package webgui;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.ElementClickInterceptedException;
import org.openqa.selenium.ElementNotInteractableException;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;

import java.time.Duration;

import static org.junit.jupiter.api.Assertions.*;

class SomeTestScenario {

    @Test void someTestCase() {
        WebDriverManager.chromedriver().setup();

        ChromeDriver driver = new ChromeDriver();

        /** Zadanie:
         * Idz do https://www.selenium.dev/
         * Kliknij w Documentation z menu glownego
         * Na nowej stronie bedzie snippet z zakladkami, wybierz "kotlin"
         * U gory, w prawym gornym rogu jest wyszukiwanie - kliknij w nie
         * W oknie wyszukiwania wpisz "wait"
         * Nic nie klikaj tylko skasuj "wait" i wpisz "explicit"
         * Kliknij pierwszy element listy
         */



    }

}
